program Coliseu_Transporte;

uses
  Vcl.Forms,
  UDM in 'UDM.pas' {DM: TDataModule},
  UFrm_Cad_Usuario in 'UFrm_Cad_Usuario.pas' {Frm_Cad_Usuario},
  UFrm_Carregamento in 'UFrm_Carregamento.pas' {Frm_Carregamento},
  UFrm_CTE_Config in 'UFrm_CTE_Config.pas' {Frm_CTE_Config},
  UFrm_CTE_Motorista in 'UFrm_CTE_Motorista.pas' {Frm_CTE_Motorista},
  UFrm_CTE_Veiculo in 'UFrm_CTE_Veiculo.pas' {Frm_CTE_Veiculo},
  UFrm_CTENFE in 'UFrm_CTENFE.pas' {Frm_CTENFE},
  UFrm_Grade_CTE in 'UFrm_Grade_CTE.pas' {Frm_Grade_CTE},
  UFrm_MDF in 'UFrm_MDF.pas' {Frm_MDF},
  UFrm_MDFConfig in 'UFrm_MDFConfig.pas' {Frm_MDFCOnfig},
  UFrm_Motorista in 'UFrm_Motorista.pas' {Frm_Motorista},
  UFrm_NFE in 'UFrm_NFE.pas' {Frm_NFE},
  UFrm_Patch in 'UFrm_Patch.pas' {Frm_Patch},
  UFrm_Rellog in 'UFrm_Rellog.pas' {Frm_Rellog},
  UFrm_Seguro in 'UFrm_Seguro.pas' {Frm_Seguro},
  UFrm_Splash in 'UFrm_Splash.pas' {Frm_Splash},
  UFrm_Usuario in 'UFrm_Usuario.pas' {Frm_Usuario},
  UFrmFuncoes in 'UFrmFuncoes.pas' {FrmFuncoes},
  UFrmGrade in 'UFrmGrade.pas' {FrmGrade},
  UFrmLogin in 'UFrmLogin.pas' {FrmLogin},
  UFrmLogin_Acao in 'UFrmLogin_Acao.pas' {FrmLogin_Acao},
  UFrmNFdeCompra in 'UFrmNFdeCompra.pas' {FrmNFdeCompra},
  UFrmReboque in 'UFrmReboque.pas' {FrmReboque},
  UFrmTomador in 'UFrmTomador.pas' {FrmTomador},
  UFrmCTESequencia in 'UFrmCTESequencia.pas' {FrmCTESequencia},
  UFrm_NF_CTE in 'UFrm_NF_CTE.pas' {Frm_NF_CTE},
  UFrm_NotaFiscal_A in 'UFrm_NotaFiscal_A.pas' {Frm_NotaFiscal_A},
  UFrm_CTE_OutroDoc in 'UFrm_CTE_OutroDoc.pas' {Frm_CTE_OutroDoc},
  UFrm_Unidade in 'UFrm_Unidade.pas' {Frm_Unidade},
  UFrm_CTE_VAdicional in 'UFrm_CTE_VAdicional.pas' {Frm_CTE_VAdicional},
  UFrm_CadClientes in 'UFrm_CadClientes.pas' {Frm_CadClientes},
  UFrmCad_NOperacao in 'UFrmCad_NOperacao.pas' {FrmCad_NOperacao},
  UFrmNatureza_Operacao in 'UFrmNatureza_Operacao.pas' {FrmNatureza_Operacao},
  UFrmCad_Regiao in 'UFrmCad_Regiao.pas' {FrmCad_Regiao},
  UFrm_Regiao in 'UFrm_Regiao.pas' {Frm_Regiao},
  UFrm_ConfigSistema in 'UFrm_ConfigSistema.pas' {Frm_ConfigSistema},
  UFrm_Empresa in 'UFrm_Empresa.pas' {Frm_Empresa},
  UFrmAbout in 'UFrmAbout.pas' {FrmAbout},
  UFrm_CTE_CartaCorrecao in 'UFrm_CTE_CartaCorrecao.pas' {Frm_CTE_CartaCorrecao},
  UUFrm_Frm_CTE_GCartaCorrecao in 'UUFrm_Frm_CTE_GCartaCorrecao.pas' {Frm_CTE_GCartaCorrecao},
  UFrm_RelCTE in 'UFrm_RelCTE.pas' {Frm_RelCTE},
  UFrm_MDF_Averbacao in 'UFrm_MDF_Averbacao.pas' {Frm_MDF_Averbacao},
  UFrm_RelMDF_DT in 'UFrm_RelMDF_DT.pas' {Frm_RelMDF_DT},
  UFrmBloqueio in 'UFrmBloqueio.pas' {FrmBloqueio},
  UFrm_CTE_Averbacao in 'UFrm_CTE_Averbacao.pas' {Frm_CTE_Averbacao},
  UFrm_Conexao in 'UFrm_Conexao.pas' {Frm_Conexao},
  UFrm_GradeVeiculos in 'UFrm_GradeVeiculos.pas' {Frm_GradeVeiculos},
  UFrm_CadVeiculos in 'UFrm_CadVeiculos.pas' {Frm_CadVeiculos},
  UFrm_MDFe_AnexCTE in 'UFrm_MDFe_AnexCTE.pas' {Frm_MDFe_AnexCTE},
  Vcl.Themes,
  Vcl.Styles,
  UFrm_CTE_CHAVE in 'UFrm_CTE_CHAVE.pas' {Frm_CTE_CHAVE},
  UFrm_MDF_CHAVE in 'UFrm_MDF_CHAVE.pas' {Frm_MDF_CHAVE},
  UFrmPrincipal in 'UFrmPrincipal.pas' {Frm_Principal},
  UFrm_CTE_EMISSOR2 in 'UFrm_CTE_EMISSOR2.pas' {Frm_CTE_EMISSOR2},
  UFrm_CTE_Percurso in 'UFrm_CTE_Percurso.pas' {Frm_CTE_Percurso},
  UCDM in 'UCDM.pas' {CDM: TDataModule},
  U_FrmRelCTE_DT in 'U_FrmRelCTE_DT.pas' {Frm_RelCTE_dt},
  UFrm_Rotas in 'UFrm_Rotas.pas' {Frm_Rotas},
  UFrm_EncerraMDF in 'UFrm_EncerraMDF.pas' {Frm_EncerraMDF},
  UFrm_SelMotorista in 'UFrm_SelMotorista.pas' {Frm_SelMotorista},
  UFrm_NaoEncerrado in 'UFrm_NaoEncerrado.pas' {Frm_NaoEncerrado},
  UFrm_EncerrUF in 'UFrm_EncerrUF.pas' {Frm_EncerrUF},
  UFrm_CTEDescordo in 'UFrm_CTEDescordo.pas' {Frm_CTEDescordo},
  UFrm_Cad_Seguradora in 'UFrm_Cad_Seguradora.pas' {Frm_Cad_Seguradora},
  UFrmMotorista_Vei in 'UFrmMotorista_Vei.pas' {FrmMotorista_Vei},
  UForm_Motorista_CTE in 'UForm_Motorista_CTE.pas' {Form_Motorista_CTE},
  UFrm_Info in 'UFrm_Info.pas' {Frm_info},
  UFrm_CTEXML in 'UFrm_CTEXML.pas' {Frm_CTEXML},
  U_FrmMdfCiot in 'U_FrmMdfCiot.pas' {Frm_MDFCiot},
  UFrm_GradeCCorrecao in 'UFrm_GradeCCorrecao.pas' {Frm_GradeCCorrecao};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFrm_Principal, Frm_Principal);
  Application.CreateForm(TFrmFuncoes, FrmFuncoes);
  Application.CreateForm(TFrm_GradeCCorrecao, Frm_GradeCCorrecao);
  Application.Run;
end.
